version: '3.0'
services:
  streetmerchant:
    image: acrtestmatthias.azurecr.io/streetmerchant:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    env_file:
      - dotenv
